name: E2E Testing
on:
  pull_request:
    branches:
      - master
      - develop
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build:ci
          start: npm run deploy:ci
          wait-on: 'http://localhost:3000'
          browser: chrome
